package com.biography.aws.dynamodbfunctions;

import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Person")
public class PersonDB {
	
	@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey(attributeName = "id")
	private int id;
	
	@DynamoDBAttribute
	private String name;
	
	@DynamoDBAttribute(attributeName="address")
	private String address;
	
	@DynamoDBAttribute
	private int age;
	
	@DynamoDBAttribute(attributeName = "accounts")
	private List<String> accounts;
	
	//DynamoDBIgnore
	//DynamoDBIndexHashKey
	//@DynamoDBRangeKey
	//query vs scan
	
	public PersonDB() {
		
	}
	
	public PersonDB(int id, String name, String address, int age) {
		super();
		this.id = id;
		this.name = name;
		this.address = address;
		this.age = age;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public int getAge() {
		return age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	@Override
	public String toString() {
		return "Product [id=" + id + ", name=" + name + ", address=" + address + ", age=" + age + "]";
	}
	


}
